#!/bin/sh
#/ Usage: git pr [<branch>]
#/ Open the pull request page for <branch>, or the current branch if not
#/ specified. Lands on the new pull request page when no PR exists yet.
#/ The branch must already be pushed

# Based on script from @rtomayko
set -e

urlencode() {
    # urlencode <string>

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%s' "$c" | xxd -p -c1 |
                   while read c; do printf '%%%s' "$c"; done ;;
        esac
    done
}


# usage message
if [ "$1" == "--help" -o "$1" == '-h' ]; then
    grep ^#/ "$0" | cut -c4-
    exit
fi

remote_url=$(git config --get remote.origin.url)
echo $remote_url
repo_with_owner=$(echo $remote_url | perl -pe's/(git@|https:\/\/)?github.com(-rakuten)?(:|\/)(\/)?([\w\-]+)\/([\w|-]+)(.git)?/$5\/$6/')

# figure out the branch
branch=${1:-"$(git symbolic-ref HEAD | sed 's@refs/heads/@@')"}

# check that the branch exists in the origin remote first
if git rev-parse "refs/remotes/origin/$branch" 1>/dev/null 2>&1; then
    # escape forward slashes
    branch=${branch//\//\%2f}
    # escape hashtags
    branch=${branch//#/\%23}

    url="https://github.com/$repo_with_owner/pull/$branch"
    echo $url
    exec open $url
else
    echo "error: branch '$branch' does not exist on the origin remote." 1>&2
    echo "       try again after pushing the branch"
fi
